CREATE TABLE public.contest_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    contest_id UUID NOT NULL REFERENCES public.contests(id) ON DELETE CASCADE,
    entry_id UUID NOT NULL REFERENCES public.contest_entries(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(user_id, contest_id)
);

ALTER TABLE public.contest_votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own votes"
ON public.contest_votes
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own votes"
ON public.contest_votes
FOR INSERT
WITH CHECK (auth.uid() = user_id);
