-- Drop the existing table
DROP TABLE IF EXISTS public.transactions;

-- Recreate the table with a more detailed structure
CREATE TABLE public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    transaction_id TEXT NOT NULL UNIQUE,
    gateway TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    currency TEXT NOT NULL,
    status TEXT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add indexes for common queries
CREATE INDEX idx_transactions_user_id ON public.transactions(user_id);
CREATE INDEX idx_transactions_gateway ON public.transactions(gateway);

-- Add comments for clarity
COMMENT ON TABLE public.transactions IS 'Stores all payment gateway transactions.';
COMMENT ON COLUMN public.transactions.transaction_id IS 'The unique identifier for the transaction from the payment provider.';
COMMENT ON COLUMN public.transactions.gateway IS 'The payment gateway used (e.g., stripe, paystack, flutterwave).';
COMMENT ON COLUMN public.transactions.status IS 'The status of the transaction (e.g., success, pending, failed).';
